# Generated by Django 5.1.7 on 2025-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeProduct', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('image', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
