# Generated by Django 5.1.7 on 2025-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_usermodel_address_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
